version: "3"

services:

    db:
        image: mysql
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./backend/src/database/migrations:/var/lib/mysql
        restart: always
    
    backend:
        build: "./backend"
        container_name: backend-container
        restart: always
        ports:
            - "5000:5000"
        depends_on:
             - db

    frontend:
        build: "./frontend"
        container_name: frontend-container
        restart: always
        ports:
            - "3000:3000"
